language: node_js
node_js:
- node
- '7'
- '6'
deploy:
  provider: npm
  email: alexandre@bintz.io
  api_key:
    secure: r+fXo/USZJdGUKhtY4ddI8uMRUKTkd170rNGClHg8mbrG5KF1C1h8gt0LNL80TswcYwUuhsBfYXVcmVGQqhY/SkbySwfrGVbt0R2km3FFrXNKU5RNTC/hreQcsGutlepF5/KEwnli4zSoFhIyFRA5A2h4DXHdVlZ9i3wvRAhO9OFm/zPs5Q77FEtFbBjNLewxeh7Bu+v5MGIfVoFpGgRkNF+BPN0JIFQz1jl72MkNR92hfn3jYHvqoIzKWxK50mbPavIm9qh688NyRXODUqSXjpFgMw6kqwyGeRRhck9ovH3ZhzD/xyJo7e3MfxiPRQ6OD+ApBmy1J3nLA7KqhY9rV92i/U+kGJuQgTI8J3UJqf/cqLypbk23ofJSoTTdrwqabAe20DxtTls5bkr9eYcqbcZ2Tja2IbYtZJjZTYr3vWB7LsPenhwAOdhEXsdYBtiXr4wk++KrcmJwtNap9u9+aEKPdDhwfGwf0/PIYy5ayE3rARf8MKCX9slRyQNFwjxZxzDN61/XHSDume3FzXxRipSnO2oKZ/hcCdKbpBwsgRS6eX9qUMZHemQNm9mqm2AHNDuWhvsS+ZJ6IBaFi940NjMb+lAN3MGqzt+Y+g/WyA6b4QOek6WfvLCps1W/F1lMK9CkPBVSqr25SU5RA50Oq0HfvDV2RnyhkxsFZT7nYA=
  on:
    tags: true
    node: node
